archetypeDir: "archetypes"
contentDir:   "content"
layoutDir:    "layouts"
publishDir:   "public"
dataDir:      "data"
staticDir:    "static"

taxonomies:
  tag:        "tags"
  category:   "categories"
  authors:    "authors"

disqusShortname:  "cercal-io"
defaultExtension: "html"
metaDataFormat:   "yaml"
googleAnalytics:  "UA-112106232-1"

pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsOptions:    "linenos=true"

languageCode: "pt"
defaultContentLanguage: "pt"
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: false

languages:
  en:
    title: "jpcercal.com"
    locale: "en"
    description: "High quality and variety of subjects, including tips from programming to lifestyle but written in our style and we are not talking about CSS."
  pt:
    title: "jpcercal.com"
    locale: "pt"
    description: "Alta qualidade e variedade de assuntos, incluindo desde dicas de programação à estilo de vida, mas no nosso estilo e não estamos falando de CSS."

rssLimit: 15
paginate: 10
paginatePath: "page"
permalinks:
  posts:   /:slug/
  authors: /authors/:slug/

stepAnalysis: true
noChmod:      false
noTimes:      false
buildFuture:  false
buildExpired: false
relativeURLs: false
canonifyURLs: false

logFile:      "hugo.log"
log:          true
verbose:      false
verboseLog:   true

disablePathToLower:         false
watch:                      true
enableRobotsTXT:            true
disableHugoGeneratorInject: true
enableEmoji:                false

footnoteAnchorPrefix:       ""
footnoteReturnLinkContents: ""

ignoreFiles: 
  - "Thumbs\\.db$"
  - "\\.DS_Store$"
  - "\\.log$"
  - "\\.lock$"
  - "\\.sw?$"
